<a href="https://colab.research.google.com/github/Jessie-Grewal/Neur265/blob/main/coding_homework_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Coding Homework #2

**Instructions:**

1. Make a *Markdown Cell* that contains the following information:
- Your name (small header)
- The name of this class (italicized)
- The date (bolded)

2. Make a *Code Cell* that imports <code>numpy</code> as <code>np</code>, <code>matplotlib.pyplot</code> as <code>plt</code>, <code>statistics</code> as <code>st</code>.

3. Make a *Code Cell* that imports your <code>v_rest1.csv</code> and <code>v_rest2.csv</code> files as <code>numpy</code> arrays called <code>v_rest1</code> and <code>v_rest2</code> respectively. You're used to doing this with the <code>pd.read_csv</code> function for <code>pandas</code>, but can accomplish the same thing using the <code>np.loadtxt</code> function for <code>numpy</code>.

4. Make a *Code Cell* that concatenates <code>v_rest1</code> and <code>v_rest2</code> into a matrix with 2 rows and 13 columns named <code>v_rest</code>.

5. Make a *Code Cell* that prints the <code>size</code> of <code>v_rest</code>.

6. Make a *Code Cell* that returns the first row of <code>v_rest</code>.

7. Make a *Code Cell* that returns the sum of the values in the third column of <code>v_rest</code>. You can accomplish this by using <code>v_rest[].sum()</code>, with your index inside of the brackets. As an example, if I wanted to return the sum of the first row of <code>v_rest</code>, I could use <code>v_rest[0].sum()</code> to get my answer.

8. Make a *Code Cell* that returns the second-to-last value in the second row of <code>v_rest</code> (use negative indexing for the column value).

9. Create a *Code Cell* that makes a histogram of the values in the first row of <code>v_rest</code> (you can do this by using the <code>plt.hist()</code> function). Label your axes.

10. Create a *Code Cell* that takes the mean of the values in the first row of <code>v_rest</code>, and assigns the mean to a variable called <code>v_rest_mean_1</code>. Do the same thing for the second row of <code>v_rest</code>, and assign the mean value of the second row to a variable called <code>v_rest_mean_2</code>. You can get the means by using the <code>st.mean()</code> function (remember to put what you want the mean *of* inside the parentheses of the function).

11. Create a *Markdown Cell* that describes the difference in means between the two rows. Which one is bigger?

12. How can we test whether the difference in means is *meaningful* (statistically significant)? When we're comparing two means, we can use a t-test (assuming the data are normally distributed). To use a t-test on our data, we will first need to import the <code>scipy</code> package. Create a new *Code Cell* that runs the following:

<code>
import scipy.stats as stats
</code>

13. Now, we can perform a t-test on the two rows of <code>v_rest</code>. To do this, create a new *Code Cell* that uses the <code>stats.ttest_ind()</code> function - for example:

<code>
stats.ttest_ind(row1, row2)
</code>

Replace <code>row1</code> and <code>row2</code> in this case with the first and second rows, respectively, of <code>v_rest</code>.

14. Make a *Markdown Cell* that describes the results of your t-test. You should have <code>statistic</code> variable and a <code>pvalue</code> variable. The way to interpret your p-value is as a probability - specifically, the probability that the mean of one distribution could be found in the second distribution. Typically, results are considered to be "statistically significant" if the probability is lower than 5% - or 0.05. What is your p-value? Based on this p-value, do you think it is likely that the means are significantly different, or do you think it is likely that they are not?

15. Make sure to add at least one line with a <code>#</code> in front of it to each *Code Cell* to describe what each cell does.

16. Save a copy of this notebook to your GitHub repo with the title "coding_homework_2.ipynb".

### Jessie Grewal

_Neur 265: Intro to Neural Data Analysis_

Date: __2-24-2023__

In [6]:
# Importing data managament packages- numpy, matplotlib, and statistics
import numpy as np
import matplotlib.pyplot as plt
import statistics as st

In [27]:
# Importing vrest1 and vrest2 datafiles as numpy arrays
vrest_1_url = 'https://raw.githubusercontent.com/Jessie-Grewal/Neur265/main/vrest_1.csv'
vrest_2_url = 'https://raw.githubusercontent.com/Jessie-Grewal/Neur265/main/vrest_2.csv'

v_rest1 = np.loadtxt(vrest_1_url).reshape(13,1)
print (v_rest1)
v_rest2 = np.loadtxt(vrest_2_url).reshape(13,1)
print(v_rest2)

[[-65.22357635]
 [-69.37517062]
 [-74.64432664]
 [-65.7697915 ]
 [-75.19783554]
 [-72.78378732]
 [-68.68115692]
 [-66.56558638]
 [-70.88484573]
 [-78.4155338 ]
 [-78.96686068]
 [-66.69574314]
 [-75.32606021]]
[[-66.96053925]
 [-78.32640266]
 [-73.75214462]
 [-73.38384247]
 [-68.27419662]
 [-69.59182472]
 [-72.79958153]
 [-72.99005714]
 [-67.65620518]
 [-71.15641308]
 [-76.08525009]
 [-59.41326904]
 [-78.42680359]]


In [28]:
v_rest = np.concatenate((v_rest1, v_rest2), axis = 1)
print (v_rest)

[[-65.22357635 -66.96053925]
 [-69.37517062 -78.32640266]
 [-74.64432664 -73.75214462]
 [-65.7697915  -73.38384247]
 [-75.19783554 -68.27419662]
 [-72.78378732 -69.59182472]
 [-68.68115692 -72.79958153]
 [-66.56558638 -72.99005714]
 [-70.88484573 -67.65620518]
 [-78.4155338  -71.15641308]
 [-78.96686068 -76.08525009]
 [-66.69574314 -59.41326904]
 [-75.32606021 -78.42680359]]


Object `arange` not found.
